id = "haku-dark-theme"
name = "Haku Dark"
version = "0.0.1"
schema_version = 1
authors = ["Arthur Brussee <arthur.brussee@gmail.com>"]
description = "A soothing dark theme. An editor full off soot, made into a high class place."
repository = "https://github.com/ArthurBrussee/haku_dark"
